### ISSUE TITLE
can't get it to run after pip install

### ISSUE THREAD

**Issue by hcdenbakker** [Phelimb/BIGSI#19]
Hey Phelim, 

Trying to run this on my own server, without using docker. 

Just 

```
pip install cbg
```
gives me this error:
```
Collecting cbg
  Using cached cbg-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vr6gdw6q/cbg/setup.py", line 4, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vr6gdw6q/cbg/
```
So I am trying to install it with pip from the cloned repo:
```
pip install ~/cbg
```
Seems to install fine without errors, but gives troubles when I am trying to run cbg:
```
cbg init example-data/db --k 21 --m 1000 --h 3

Traceback (most recent call last):
  File "/home/henk/anaconda3/bin/cbg", line 11, in <module>
    load_entry_point('cbg==0.1.5', 'console_scripts', 'cbg')()
  File "/home/henk/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/henk/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/henk/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/henk/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/henk/anaconda3/lib/python3.6/site-packages/cbg/__init__.py", line 3, in <module>
    from cbg.graph.probabilistic import CBG
  File "/home/henk/anaconda3/lib/python3.6/site-packages/cbg/graph/__init__.py", line 1, in <module>
    from cbg.graph.probabilistic import CBG
  File "/home/henk/anaconda3/lib/python3.6/site-packages/cbg/graph/probabilistic.py", line 36, in <module>
    from cbg.scoring import Scorer
ModuleNotFoundError: No module named 'cbg.scoring'
```
Scorer seems to be in cbg.scoring.score, and somehow this scoring module does not seem to be in the site-packages/cbg folder.

**Comment by hcdenbakker** [comment]
Hey Phelim,
Everything seems to install/work properly now.
-Henk

**Comment by Phelimb** [comment]
@hcdenbakker Somehow missed this issue, sorry. Did you use the new instructions? I've had trouble getting it set up with pip as there's some requirements that don't seem to work with setuptools easily. The instructions at https://bigsi.readme.io/ should work now.

**Comment by hcdenbakker** [comment]
Yes, I used the new instructions and it worked flawlessly, passed all the tests and I could apply it to some of my own data.

-Henk

**Comment by Phelimb** [comment]
Great!
