### ISSUE TITLE
Version 0.3.2 - 'SyntaxError: invalid syntax' - Solution

### ISSUE THREAD

**Issue by erichards52** [Phelimb/BIGSI#46]
Found solution when the following error message was returned upon calling any of the BIGSI commands (i.e.: `bigsi`) using version 0.3.2:

```
Traceback (most recent call last):

 File "/homes/richards/.local/bin/bigsi", line 7, in <module>

   from bigsi.__main__ import main

 File "/homes/richards/.local/lib/python3.4/site-packages/bigsi/__init__.py", line 3, in <module>

   from bigsi.graph.bigsi import BIGSI

 File "/homes/richards/.local/lib/python3.4/site-packages/bigsi/graph/__init__.py", line 1, in <module>

   from bigsi.graph.bigsi import BIGSI

 File "/homes/richards/.local/lib/python3.4/site-packages/bigsi/graph/bigsi.py", line 5, in <module>

   from bigsi.constants import DEFAULT_CONFIG

 File "/homes/richards/.local/lib/python3.4/site-packages/bigsi/constants.py", line 17

   **DEFAULT_PARAMETERS,

    ^

SyntaxError: invalid syntax
```

SOLUTION:
Make sure to install both `static_lib` & `shared_lib` when building rocksdb & add to PATH:
`DEBUG_MODE=0 make static_lib shared_lib` (in rocksdb dir)
`export CPLUS_INCLUDE_PATH=<path_to_rocksdb_dir>/include`
`export LIBRARY_PATH=<path_to_rocksdb_dir>`
`export LD_LIBRARY_PATH=<path_to_rocksdb_dir`

**Comment by AngelaMuraya** [comment]
Thank you. I'll try it out.

**Comment by Phelimb** [comment]
Thanks @erichards52
