### ISSUE TITLE
We encountered an error when inserting the bloom filters into the index.

### ISSUE THREAD

**Issue by pany-vet** [Phelimb/BIGSI#54]
**We encountered the following error when inserting the bloom filters into the index. And we don't know how to solve this problem.** 
`Traceback (most recent call last):
  File "/usr/local/bin/bigsi", line 11, in <module>
    load_entry_point('bigsi==0.3.5', 'console_scripts', 'bigsi')()
  File "/usr/local/lib/python3.6/dist-packages/bigsi/__main__.py", line 305, in main
    API.cli()
  File "hug/api.py", line 390, in hug.api.CLIInterfaceAPI.__call__
  File "hug/interface.py", line 551, in hug.interface.CLI.__call__
  File "hug/interface.py", line 547, in hug.interface.CLI.__call__
  File "hug/interface.py", line 100, in hug.interface.Interfaces.__call__
  File "/usr/local/lib/python3.6/dist-packages/bigsi/__main__.py", line 142, in build
    assert len(samples) == len(bloomfilters)
AssertionError
`
**We have python 3.6 in Ubuntu 18.04 workstation and used berkeleydb to store data. We are trying to construct a BIGSI following the tutorials in [https://bigsi.readme.io/docs/your-first-bigsi](url). We will be very grateful if you can help us.**

**Comment by Phelimb** [comment]
@pany-vet can you post your commandline. It looks like you haven't specified the same number of sample names as bloom filters. 

It might be easier to use a tsv to specify the bloom filters filepaths and sample names and build with
`bigsi build -f example-data/build_file.tsv`

E.g. https://raw.githubusercontent.com/Phelimb/BIGSI/build_from_file/example-data/build_file.tsv

**Comment by pany-vet** [comment]
@Phelimb Thank you very much for your help! It works!
